Locally bind to specific address via new LocalIpAddress property
robinrodricks/FluentFTP pull request #719
Opened 2021-04-30 16:53 UTC by daviddenis-stx

As promised in discussion in https://github.com/robinrodricks/FluentFTP/issues/713 

A PR with only *.cs files

Not sure it will build with all targets (net20 and such, who still uses that anyway ?)

2021-05-01 03:25 UTC, robinrodricks commented
Awesome, I'll check it out!

2021-05-01 03:32 UTC, robinrodricks requested changes
Great work with the example code and helpers. However some changes to the `FtpSocketStream` class could be reverted if possible so that other users are not impacted. If not possible, let me know. Thanks!

2021-05-01 03:32 UTC, robinrodricks commented on FluentFTP/Streams/FtpSocketStream.cs
> -			IPAddress[] addresses = Dns.GetHostAddressesAsync(host).Result;
Is this change needed?

2021-05-01 03:32 UTC, robinrodricks commented on FluentFTP/Client/FtpClient_Properties.cs
> +		public IPEndPoint LocalEndPoint => this.m_stream.LocalEndPoint;
Read only or editable?

2021-05-01 03:32 UTC, robinrodricks commented on FluentFTP/Streams/FtpSocketStream.cs
> -					RemoteEndPoint = new IPEndPoint(addresses[i], port)
Is this change needed?

2021-05-04 06:48 UTC, daviddenis-stx commented on FluentFTP/Streams/FtpSocketStream.cs
> -			IPAddress[] addresses = Dns.GetHostAddressesAsync(host).Result;
Strange, i still have this line in my local code, I must have missed something while rebasing

2021-05-04 06:49 UTC, daviddenis-stx commented on FluentFTP/Streams/FtpSocketStream.cs
> -					RemoteEndPoint = new IPEndPoint(addresses[i], port)
Same here, I have that locally, unchanged

2021-05-04 06:49 UTC, daviddenis-stx commented on FluentFTP/Streams/FtpSocketStream.cs
> -					RemoteEndPoint = new IPEndPoint(addresses[i], port)
looks like whitespace problems

2021-05-04 06:53 UTC, daviddenis-stx commented on FluentFTP/Client/FtpClient_Properties.cs
> +		public IPEndPoint LocalEndPoint => this.m_stream.LocalEndPoint;
It shouldn't be changed if the connection state is already "connected" (it would have no effect since we call BindLocallyIfNeeded() from the Connect() and ConnectAsync() method)

2021-05-04 07:00 UTC, daviddenis-stx commented on FluentFTP/Streams/FtpSocketStream.cs
> -			IPAddress[] addresses = Dns.GetHostAddressesAsync(host).Result;
Hmmm, I remember, just checked if the async version was more prone to list IPv6 addresses (it wasn't). 

We probably need to use something else here for proper IPv6 resolving support (you told me about some co-routine already present in the code, capable of doing lookups). On my first patch I used DnsClient which resolves correctly.

If GetHostAddresses() won't return IPv6 addresses (that happens when the default route is IPv4). You won't be able to connect to hosts that have also IPv6 addresses. Which is a problem if you bind locally to an IPv6 interface that is capable to reach that IPv6 addresses host also has. It ends up with locally binding to IPv6 interface and trying to connect to an IPv4 host, that can't work.

2021-05-04 07:09 UTC, robinrodricks commented on FluentFTP/Streams/FtpSocketStream.cs
> -			IPAddress[] addresses = Dns.GetHostAddressesAsync(host).Result;
So can I revert this or is it needed to make your functionality work? If it is needed I can use a flag (option) to let users enable/disable this? Or are you sure it won't break the existing functionality?

2021-05-04 07:12 UTC, daviddenis-stx commented
This does the same stuff [thing.DoSomethingAsync().Result and thing.DoSomething()]
It’s safe to revert

From: Robin Rodricks ***@***.***>
Sent: 04 May 2021 09:10
To: robinrodricks/FluentFTP ***@***.***>
Cc: David Denis ***@***.***>; Author ***@***.***>
Subject: Re: [robinrodricks/FluentFTP] Locally bind to specific address via new LocalIpAddress property (#719)


@robinrodricks commented on this pull request.

________________________________

In FluentFTP/Streams/FtpSocketStream.cs<https://github.com/robinrodricks/FluentFTP/pull/719#discussion_r625554035>:

> @@ -815,7 +821,7 @@ public class FtpSocketStream : Stream, IDisposable {

               /// <param name="ipVersions">Internet Protocol versions to support during the connection phase</param>

               public void Connect(string host, int port, FtpIpVersion ipVersions) {

 #if CORE

-                      IPAddress[] addresses = Dns.GetHostAddressesAsync(host).Result;

So can I revert this or is it needed to make your functionality work? If it is needed I can use a flag (option) to let users enable/disable this? Or are you sure it won't break the existing functionality?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/robinrodricks/FluentFTP/pull/719#discussion_r625554035>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AMB4IIQ7UPJ5PWNINB2Y7MDTL6MUVANCNFSM434XXJMQ>.

2021-05-04 07:23 UTC, robinrodricks commented on FluentFTP/Streams/FtpSocketStream.cs
> -					RemoteEndPoint = new IPEndPoint(addresses[i], port)
Understood

2021-05-04 07:23 UTC, robinrodricks commented on FluentFTP/Client/FtpClient_Properties.cs
> +		public IPEndPoint LocalEndPoint => this.m_stream.LocalEndPoint;
Thanks

2021-05-04 07:24 UTC, robinrodricks commented on FluentFTP/Streams/FtpSocketStream.cs
> -			IPAddress[] addresses = Dns.GetHostAddressesAsync(host).Result;
Understood

2021-05-04 07:24 UTC, robinrodricks commented
Great, thanks.

2021-05-04 13:13 UTC, merged

2021-05-04 13:14 UTC, robinrodricks commented
Thanks for this!

2021-05-04 13:15 UTC, daviddenis-stx commented
My pleasure 😊

From: Robin Rodricks ***@***.***>
Sent: 04 May 2021 15:15
To: robinrodricks/FluentFTP ***@***.***>
Cc: David Denis ***@***.***>; Author ***@***.***>
Subject: Re: [robinrodricks/FluentFTP] Locally bind to specific address via new LocalIpAddress property (#719)


Thanks for this!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/robinrodricks/FluentFTP/pull/719#issuecomment-831932224>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AMB4IIUWQWOPEPQMPARGHITTL7XNPANCNFSM434XXJMQ>.

2021-05-04 13:17 UTC, daviddenis-stx commented
It's probable that without the proper DNS resolving for IPv6, people will have to use the IPv6 addresses both for local and remote :) Can you point me to the place where you do DNS resolving in the current code ? I'll try it

2021-05-04 13:33 UTC, robinrodricks commented
These are all I can find:
1. https://github.com/robinrodricks/FluentFTP/blob/master/FluentFTP/Streams/FtpSocketStream.cs#L824
2. https://github.com/robinrodricks/FluentFTP/blob/master/FluentFTP/Streams/FtpSocketStream.cs#L939

2021-05-05 14:40 UTC, robinrodricks commented
Added to docs.

https://github.com/robinrodricks/FluentFTP/wiki/FTP-Connection#socket-settings

2021-05-06 06:03 UTC, daviddenis-stx commented
Thanks a lot Robin 😊 Will give it a try. Keep you posted.

From: Robin Rodricks ***@***.***>
Sent: 05 May 2021 16:11
To: robinrodricks/FluentFTP ***@***.***>
Cc: David Denis ***@***.***>; Author ***@***.***>
Subject: Re: [robinrodricks/FluentFTP] Locally bind to specific address via new LocalIpAddress property (#719)


Released. I did some refactoring / cleanup too.

Can you test it and see that nothing is broken in your new functionality? Btw prop is now called SocketLocalIp and others with Socket prefix to keep the property naming structured.

https://www.nuget.org/packages/FluentFTP/34.0.0

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/robinrodricks/FluentFTP/pull/719#issuecomment-832719620>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AMB4IIR2ONNTK2HZVIEBXCDTMFGWHANCNFSM434XXJMQ>.